<?php

namespace AppBundle\Repository;

/**
 * SalonMessagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalonMessagesRepository extends \Doctrine\ORM\EntityRepository
{
}
