<?php

namespace AppBundle\Repository;

/**
 * UserOeuvreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserOeuvreRepository extends \Doctrine\ORM\EntityRepository
{
	public function avgRatingBook($book)
    {
        $qb = $this->createQueryBuilder('a');
        $qb->select('AVG(a.rating) AS moyenne')
            ->where('a.oeuvre = :book')
            ->setParameter('book', $book);

        return $qb->getQuery()->getSingleScalarResult();
    }
}
