<?php

namespace AppBundle\Repository;

/**
 * UserOeuvreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserOeuvreRepository extends \Doctrine\ORM\EntityRepository
{
}
